# Site settings
title: Resumely
description: Build your best resume, get your dream job!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://resumely.co" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Resumely
user_description: 
user_title: Under Construction
email: #
twitter_username: #
github_username: resumely
gplus_username:  #

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
